### ISSUE TITLE
Can't load tree from editor json

### ISSUE THREAD

**Issue by DIGarnier** [behavior3/behavior3py#3]
Passing trees made with the online editor containing decorators outputs this: 
I'm using python 2.7

```
Traceback (most recent call last):  File "test.py", line 10, in <module>    tree.load(data_tree)
  File "/home/b3/core/behaviortree.py", line 35, in load
    node = cls()
TypeError: __init__() missing 1 required positional argument: 'child'
```

The tree in question is this simple one:

![tree](https://user-images.githubusercontent.com/26147736/31526365-53a2ddb8-af94-11e7-9bbf-ae26e92e1538.jpg)

It seems like the node's constructor is always being called without children even if it needs one.

**Comment by benfrussell** [comment]
I just ran into this issue, did you ever figure out a workaround?

**Comment by DIGarnier** [comment]
The workaround would be to build your tree by hand, which I did and it works. I have a project on my github you can peruse if you need inspiration!

**Comment by benfrussell** [comment]
Digging around the JS version I actually found that all of the decorators have that same child parameter, but defaulted to null. I added the default to None for that parameter in my fork (as well as removing some Python 2 dependencies) and no more problems!

https://github.com/Koraken/behavior3py
